import { getJsonCompletion } from "../services/groq";

export interface SeederItem {
    name: string;
    icon: string;
    iconLibrary: string;
}

// Curated list of VALID icons for each library (commonly used, verified to work)
const VALID_ICONS: Record<string, Set<string>> = {
    MaterialCommunityIcons: new Set([
        "account",
        "account-circle",
        "account-group",
        "alert",
        "alert-circle",
        "analytics",
        "android",
        "apple",
        "arrow-left",
        "arrow-right",
        "atom",
        "bank",
        "basketball",
        "battery",
        "bell",
        "bicycle",
        "book",
        "book-open",
        "bookmark",
        "briefcase",
        "brush",
        "bug",
        "bullhorn",
        "bus",
        "cake",
        "calculator",
        "calendar",
        "camera",
        "car",
        "cart",
        "cash",
        "cellphone",
        "chart-bar",
        "chart-line",
        "chart-pie",
        "check",
        "check-circle",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "chevron-up",
        "clipboard",
        "clock",
        "cloud",
        "code-tags",
        "cog",
        "cogs",
        "comment",
        "compass",
        "cpu-64-bit",
        "credit-card",
        "database",
        "delete",
        "desktop-mac",
        "doctor",
        "domain",
        "download",
        "earth",
        "email",
        "emoticon",
        "eye",
        "facebook",
        "file",
        "file-document",
        "filter",
        "finance",
        "fire",
        "flag",
        "flash",
        "flask",
        "flower",
        "folder",
        "food",
        "football",
        "format-paint",
        "gamepad",
        "gas-station",
        "gift",
        "github",
        "google",
        "google-analytics",
        "graph",
        "hammer",
        "hand",
        "headphones",
        "heart",
        "help",
        "help-circle",
        "home",
        "hospital",
        "human",
        "image",
        "infinity",
        "information",
        "instagram",
        "key",
        "keyboard",
        "laptop",
        "leaf",
        "library",
        "lightbulb",
        "lightning-bolt",
        "link",
        "linkedin",
        "linux",
        "lock",
        "login",
        "logout",
        "magnify",
        "map",
        "map-marker",
        "math-compass",
        "medical-bag",
        "menu",
        "message",
        "microphone",
        "microsoft",
        "minus",
        "monitor",
        "movie",
        "music",
        "network",
        "newspaper",
        "note",
        "notebook",
        "npm",
        "office-building",
        "palette",
        "paperclip",
        "pencil",
        "phone",
        "pill",
        "pin",
        "pinterest",
        "plane",
        "play",
        "plus",
        "plus-circle",
        "podcast",
        "power",
        "printer",
        "progress-check",
        "puzzle",
        "qrcode",
        "radar",
        "radio",
        "react",
        "recycle",
        "refresh",
        "remote",
        "repeat",
        "rocket",
        "ruler",
        "run",
        "sale",
        "scale-balance",
        "school",
        "script",
        "security",
        "send",
        "server",
        "settings",
        "share",
        "shield",
        "shopping",
        "sigma",
        "signal",
        "sitemap",
        "skull",
        "slack",
        "sleep",
        "speedometer",
        "spray",
        "square-root",
        "stack-overflow",
        "star",
        "stethoscope",
        "store",
        "sun",
        "sword",
        "table",
        "tablet",
        "tag",
        "target",
        "teach",
        "telescope",
        "television",
        "test-tube",
        "text",
        "theater",
        "thermometer",
        "thumb-up",
        "timer",
        "tools",
        "tooth",
        "train",
        "translate",
        "trash-can",
        "tree",
        "trending-up",
        "trophy",
        "truck",
        "tune",
        "twitter",
        "umbrella",
        "undo",
        "upload",
        "usb",
        "video",
        "view-grid",
        "wallet",
        "water",
        "weather-sunny",
        "web",
        "weight",
        "wheelchair",
        "wifi",
        "window-maximize",
        "wrench",
        "xml",
        "youtube",
        "zip-box"
    ]),
    MaterialIcons: new Set([
        "account-balance",
        "account-box",
        "account-circle",
        "add",
        "add-circle",
        "alarm",
        "analytics",
        "android",
        "announcement",
        "apps",
        "arrow-back",
        "arrow-forward",
        "assignment",
        "attach-file",
        "attachment",
        "audiotrack",
        "backup",
        "bar-chart",
        "battery-full",
        "bookmark",
        "brush",
        "build",
        "business",
        "cached",
        "cake",
        "calculate",
        "calendar-today",
        "camera",
        "cancel",
        "card-giftcard",
        "category",
        "chat",
        "check",
        "check-circle",
        "chevron-left",
        "chevron-right",
        "class",
        "cloud",
        "code",
        "collections",
        "comment",
        "computer",
        "construction",
        "contact-mail",
        "contacts",
        "content-copy",
        "credit-card",
        "dashboard",
        "delete",
        "description",
        "desktop-mac",
        "developer-mode",
        "devices",
        "dns",
        "done",
        "download",
        "drafts",
        "edit",
        "email",
        "equalizer",
        "error",
        "event",
        "exit-to-app",
        "explore",
        "extension",
        "face",
        "favorite",
        "feedback",
        "file-copy",
        "filter-list",
        "flag",
        "flight",
        "folder",
        "format-paint",
        "forum",
        "games",
        "gavel",
        "gesture",
        "get-app",
        "grade",
        "group",
        "healing",
        "health-and-safety",
        "hearing",
        "help",
        "history",
        "home",
        "hourglass-empty",
        "http",
        "https",
        "image",
        "inbox",
        "info",
        "input",
        "insert-chart",
        "keyboard",
        "label",
        "language",
        "laptop",
        "launch",
        "layers",
        "leaderboard",
        "library-books",
        "lightbulb",
        "link",
        "list",
        "local-hospital",
        "location-on",
        "lock",
        "login",
        "logout",
        "mail",
        "map",
        "menu",
        "menu-book",
        "message",
        "mic",
        "model-training",
        "monetization-on",
        "money",
        "more-horiz",
        "movie",
        "music-note",
        "nature",
        "navigation",
        "near-me",
        "network-check",
        "note",
        "notifications",
        "offline-bolt",
        "palette",
        "payment",
        "pending",
        "people",
        "person",
        "phone",
        "photo",
        "pie-chart",
        "place",
        "play-arrow",
        "playlist-add",
        "power",
        "print",
        "psychology",
        "public",
        "question-answer",
        "receipt",
        "record-voice-over",
        "refresh",
        "report",
        "rocket-launch",
        "room",
        "save",
        "schedule",
        "school",
        "science",
        "search",
        "security",
        "send",
        "settings",
        "share",
        "shield",
        "shopping-cart",
        "smart-toy",
        "speed",
        "sports",
        "star",
        "storage",
        "store",
        "support",
        "sync",
        "tablet",
        "tag",
        "terminal",
        "text-fields",
        "theaters",
        "thumb-up",
        "timeline",
        "today",
        "translate",
        "trending-up",
        "tune",
        "tv",
        "upload",
        "verified",
        "visibility",
        "volunteer-activism",
        "warning",
        "water",
        "web",
        "wifi",
        "work",
        "workspace-premium",
        "youtube-searched-for",
        "zoom-in"
    ]),
    FontAwesome: new Set([
        "adjust",
        "amazon",
        "ambulance",
        "anchor",
        "android",
        "apple",
        "archive",
        "arrow-left",
        "arrow-right",
        "at",
        "balance-scale",
        "ban",
        "bank",
        "bar-chart",
        "barcode",
        "bars",
        "battery-full",
        "bed",
        "beer",
        "bell",
        "bicycle",
        "bitcoin",
        "black-tie",
        "bluetooth",
        "bold",
        "bolt",
        "bomb",
        "book",
        "bookmark",
        "briefcase",
        "btc",
        "bug",
        "building",
        "bullhorn",
        "bus",
        "calculator",
        "calendar",
        "camera",
        "car",
        "caret-down",
        "caret-up",
        "certificate",
        "chain",
        "check",
        "check-circle",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "chevron-up",
        "child",
        "circle",
        "clipboard",
        "clock-o",
        "cloud",
        "code",
        "code-fork",
        "coffee",
        "cog",
        "cogs",
        "comment",
        "comments",
        "compass",
        "copyright",
        "credit-card",
        "crop",
        "cube",
        "cubes",
        "cut",
        "dashboard",
        "database",
        "desktop",
        "diamond",
        "dollar",
        "download",
        "dribbble",
        "dropbox",
        "edit",
        "ellipsis-h",
        "envelope",
        "eraser",
        "eur",
        "exchange",
        "exclamation",
        "exclamation-circle",
        "eye",
        "facebook",
        "fighter-jet",
        "file",
        "file-code-o",
        "file-excel-o",
        "file-image-o",
        "file-pdf-o",
        "file-powerpoint-o",
        "file-text",
        "file-word-o",
        "film",
        "filter",
        "fire",
        "fire-extinguisher",
        "flag",
        "flask",
        "folder",
        "folder-open",
        "font",
        "forward",
        "frown-o",
        "futbol-o",
        "gamepad",
        "gavel",
        "gear",
        "gears",
        "gift",
        "github",
        "gitlab",
        "glass",
        "globe",
        "google",
        "graduation-cap",
        "group",
        "hacker-news",
        "hand-o-left",
        "hand-o-right",
        "handshake-o",
        "hashtag",
        "hdd-o",
        "header",
        "headphones",
        "heart",
        "heartbeat",
        "history",
        "home",
        "hospital-o",
        "hourglass",
        "html5",
        "id-badge",
        "id-card",
        "image",
        "inbox",
        "industry",
        "info",
        "info-circle",
        "instagram",
        "institution",
        "key",
        "keyboard-o",
        "language",
        "laptop",
        "leaf",
        "legal",
        "lemon-o",
        "level-up",
        "life-ring",
        "lightbulb-o",
        "line-chart",
        "link",
        "linkedin",
        "linux",
        "list",
        "lock",
        "magic",
        "magnet",
        "mail-forward",
        "mail-reply",
        "male",
        "map",
        "map-marker",
        "maxcdn",
        "medkit",
        "meh-o",
        "microchip",
        "microphone",
        "minus",
        "mobile",
        "money",
        "moon-o",
        "motorcycle",
        "mouse-pointer",
        "music",
        "neuter",
        "newspaper-o",
        "object-group",
        "pagelines",
        "paint-brush",
        "paper-plane",
        "paperclip",
        "paragraph",
        "paste",
        "pause",
        "paw",
        "paypal",
        "pencil",
        "phone",
        "photo",
        "pie-chart",
        "pinterest",
        "plane",
        "play",
        "plug",
        "plus",
        "plus-circle",
        "podcast",
        "power-off",
        "print",
        "product-hunt",
        "puzzle-piece",
        "qrcode",
        "question",
        "question-circle",
        "quote-left",
        "random",
        "reddit",
        "refresh",
        "registered",
        "reply",
        "retweet",
        "road",
        "rocket",
        "rss",
        "rupee",
        "save",
        "scissors",
        "search",
        "server",
        "share",
        "share-alt",
        "shield",
        "ship",
        "shopping-bag",
        "shopping-basket",
        "shopping-cart",
        "sign-in",
        "sign-out",
        "signal",
        "sitemap",
        "slack",
        "sliders",
        "smile-o",
        "snapchat",
        "sort",
        "space-shuttle",
        "spinner",
        "spoon",
        "spotify",
        "square",
        "stack-exchange",
        "stack-overflow",
        "star",
        "steam",
        "stethoscope",
        "sticky-note",
        "stop",
        "street-view",
        "suitcase",
        "sun-o",
        "superpowers",
        "support",
        "table",
        "tablet",
        "tag",
        "tags",
        "tasks",
        "taxi",
        "terminal",
        "text-height",
        "thermometer",
        "thumbs-up",
        "ticket",
        "times",
        "times-circle",
        "tint",
        "toggle-off",
        "toggle-on",
        "trademark",
        "train",
        "trash",
        "tree",
        "trello",
        "trophy",
        "truck",
        "tumblr",
        "tv",
        "twitter",
        "umbrella",
        "underline",
        "undo",
        "university",
        "unlock",
        "upload",
        "usb",
        "usd",
        "user",
        "user-circle",
        "users",
        "venus",
        "viacoin",
        "video-camera",
        "vimeo",
        "vine",
        "wallet",
        "warning",
        "weixin",
        "whatsapp",
        "wheelchair",
        "wifi",
        "wikipedia-w",
        "windows",
        "wordpress",
        "wrench",
        "xing",
        "yahoo",
        "yelp",
        "youtube"
    ]),
    Ionicons: new Set([
        "add",
        "add-circle",
        "airplane",
        "alarm",
        "alert",
        "alert-circle",
        "analytics",
        "aperture",
        "apps",
        "archive",
        "arrow-back",
        "arrow-down",
        "arrow-forward",
        "arrow-up",
        "at",
        "attach",
        "backspace",
        "bag",
        "balloon",
        "barbell",
        "barcode",
        "baseball",
        "basket",
        "basketball",
        "battery-charging",
        "battery-full",
        "beaker",
        "bed",
        "beer",
        "bicycle",
        "bluetooth",
        "boat",
        "body",
        "bonfire",
        "book",
        "bookmark",
        "bowling-ball",
        "briefcase",
        "brush",
        "bug",
        "build",
        "bulb",
        "bus",
        "business",
        "cafe",
        "calculator",
        "calendar",
        "call",
        "camera",
        "car",
        "car-sport",
        "card",
        "cart",
        "cash",
        "cellular",
        "chatbox",
        "chatbubble",
        "checkbox",
        "checkmark",
        "checkmark-circle",
        "chevron-back",
        "chevron-down",
        "chevron-forward",
        "chevron-up",
        "clipboard",
        "close",
        "close-circle",
        "cloud",
        "cloud-download",
        "cloud-upload",
        "cloudy",
        "code",
        "code-slash",
        "cog",
        "color-fill",
        "color-palette",
        "compass",
        "construct",
        "contract",
        "copy",
        "create",
        "crop",
        "cube",
        "cut",
        "desktop",
        "diamond",
        "disc",
        "document",
        "document-text",
        "documents",
        "download",
        "ear",
        "earth",
        "easel",
        "egg",
        "ellipse",
        "enter",
        "exit",
        "expand",
        "extension-puzzle",
        "eye",
        "eyedrop",
        "fast-food",
        "female",
        "file-tray",
        "film",
        "filter",
        "finger-print",
        "fitness",
        "flag",
        "flame",
        "flash",
        "flashlight",
        "flask",
        "flower",
        "folder",
        "football",
        "funnel",
        "game-controller",
        "gift",
        "git-branch",
        "git-commit",
        "git-compare",
        "git-merge",
        "git-network",
        "git-pull-request",
        "glasses",
        "globe",
        "golf",
        "grid",
        "hammer",
        "hand-left",
        "hand-right",
        "happy",
        "hardware-chip",
        "headset",
        "heart",
        "heart-circle",
        "help",
        "help-buoy",
        "help-circle",
        "home",
        "hourglass",
        "ice-cream",
        "id-card",
        "image",
        "images",
        "infinite",
        "information",
        "information-circle",
        "journal",
        "key",
        "keypad",
        "language",
        "laptop",
        "layers",
        "leaf",
        "library",
        "link",
        "list",
        "locate",
        "location",
        "lock-closed",
        "lock-open",
        "log-in",
        "log-out",
        "logo-android",
        "logo-angular",
        "logo-apple",
        "logo-bitcoin",
        "logo-css3",
        "logo-facebook",
        "logo-firebase",
        "logo-github",
        "logo-google",
        "logo-html5",
        "logo-instagram",
        "logo-javascript",
        "logo-linkedin",
        "logo-nodejs",
        "logo-npm",
        "logo-pinterest",
        "logo-python",
        "logo-react",
        "logo-reddit",
        "logo-sass",
        "logo-slack",
        "logo-snapchat",
        "logo-stackoverflow",
        "logo-steam",
        "logo-tiktok",
        "logo-twitter",
        "logo-vue",
        "logo-whatsapp",
        "logo-windows",
        "logo-xbox",
        "logo-youtube",
        "magnet",
        "mail",
        "male",
        "man",
        "map",
        "medal",
        "medical",
        "medkit",
        "megaphone",
        "menu",
        "mic",
        "mic-off",
        "moon",
        "move",
        "musical-note",
        "musical-notes",
        "navigate",
        "newspaper",
        "notifications",
        "nuclear",
        "nutrition",
        "open",
        "options",
        "paper-plane",
        "partly-sunny",
        "pause",
        "paw",
        "pencil",
        "people",
        "person",
        "phone-portrait",
        "pie-chart",
        "pin",
        "pint",
        "pizza",
        "planet",
        "play",
        "podium",
        "power",
        "pricetag",
        "print",
        "pulse",
        "push",
        "qr-code",
        "radio",
        "rainy",
        "reader",
        "receipt",
        "recording",
        "refresh",
        "reload",
        "repeat",
        "resize",
        "restaurant",
        "return-down-back",
        "ribbon",
        "rocket",
        "rose",
        "sad",
        "save",
        "scale",
        "scan",
        "school",
        "search",
        "send",
        "server",
        "settings",
        "shapes",
        "share",
        "shield",
        "shield-checkmark",
        "shirt",
        "shuffle",
        "skull",
        "snow",
        "speedometer",
        "star",
        "stats-chart",
        "stop",
        "stopwatch",
        "storefront",
        "subway",
        "sunny",
        "swap-horizontal",
        "swap-vertical",
        "sync",
        "tablet-landscape",
        "telescope",
        "tennisball",
        "terminal",
        "text",
        "thermometer",
        "thumbs-down",
        "thumbs-up",
        "thunderstorm",
        "ticket",
        "time",
        "timer",
        "today",
        "toggle",
        "trail-sign",
        "train",
        "transgender",
        "trash",
        "trending-down",
        "trending-up",
        "triangle",
        "trophy",
        "tv",
        "umbrella",
        "unlink",
        "videocam",
        "volume-high",
        "volume-low",
        "volume-mute",
        "walk",
        "wallet",
        "warning",
        "watch",
        "water",
        "wifi",
        "wine",
        "woman",
        "wrench"
    ])
};

// Default fallback icons per item type
const FALLBACK_ICONS: Record<string, { icon: string; library: string }> = {
    skill: { icon: "school", library: "MaterialIcons" },
    interest: { icon: "star", library: "MaterialIcons" },
    course: { icon: "book", library: "MaterialCommunityIcons" },
    default: { icon: "help-circle", library: "MaterialCommunityIcons" }
};

/**
 * Validates if an icon exists in the specified library
 */
function isValidIcon(icon: string, library: string): boolean {
    const validSet = VALID_ICONS[library];
    if (!validSet) return false;
    return validSet.has(icon) || validSet.has(icon.toLowerCase());
}

/**
 * Gets a valid icon, with fallback if the provided one is invalid
 */
function getValidatedIcon(
    icon: string,
    library: string,
    itemType: string = "default"
): { icon: string; iconLibrary: string } {
    // Normalize library names
    const normalizedLibrary = library.replace(/-/g, "");

    if (isValidIcon(icon, normalizedLibrary)) {
        return { icon, iconLibrary: normalizedLibrary };
    }

    // Try to find the icon in any library
    for (const [lib, icons] of Object.entries(VALID_ICONS)) {
        if (icons.has(icon) || icons.has(icon.toLowerCase())) {
            console.warn(`Icon "${icon}" not in ${library}, but found in ${lib}`);
            return { icon: icon.toLowerCase(), iconLibrary: lib };
        }
    }

    // Use fallback
    const fallback = FALLBACK_ICONS[itemType] || FALLBACK_ICONS.default;
    console.warn(`Invalid icon "${icon}" for ${library}, using fallback: ${fallback.icon}`);
    return { icon: fallback.icon, iconLibrary: fallback.library };
}

/**
 * Validates and fixes a list of seeder items
 */
export function validateSeederItems<T extends SeederItem>(items: T[], itemType: string = "default"): T[] {
    return items.map((item) => {
        const validated = getValidatedIcon(item.icon, item.iconLibrary, itemType);
        return {
            ...item,
            icon: validated.icon,
            iconLibrary: validated.iconLibrary
        };
    });
}

export async function resolveIconsAndGenerateNew(
    itemsToEnrich: string[],
    knownItemNames: string[],
    type: "skill" | "interest",
    countToGenerate: number = 20
): Promise<SeederItem[]> {
    const chunkSize = 30;
    const results: SeederItem[] = [];

    // 1. Process items that need icons
    if (itemsToEnrich.length > 0) {
        console.log(`Enriching ${itemsToEnrich.length} ${type}s with icons...`);
        for (let i = 0; i < itemsToEnrich.length; i += chunkSize) {
            const chunk = itemsToEnrich.slice(i, i + chunkSize);
            console.log(
                `Processing ${type} enrichment chunk ${Math.ceil((i + 1) / chunkSize)} of ${Math.ceil(itemsToEnrich.length / chunkSize)}...`
            );

            try {
                const prompt = `
                    I have a list of ${type}s: ${JSON.stringify(chunk)}.
                    For each item in this list, return an object with:
                    - "name": The exact name from the input list.
                    - "icon": A suitable icon name from Expo Vector Icons (e.g., "account", "cog", "code-tags").
                    - "iconLibrary": One of "MaterialCommunityIcons", "MaterialIcons", "FontAwesome", "Ionicons".
                    
                    Return a JSON object with a key "items" which is an array of these objects.
                `;

                const response = await getJsonCompletion<{ items: SeederItem[] }>(prompt);
                if (response && response.items) {
                    // Validate icons before adding
                    const validatedItems = validateSeederItems(response.items, type);
                    results.push(...validatedItems);
                }
            } catch (e) {
                console.error(`Error processing chunk ${i} for ${type}:`, e);
                chunk.forEach((item) => {
                    const fallback = FALLBACK_ICONS[type] || FALLBACK_ICONS.default;
                    results.push({
                        name: item,
                        icon: fallback.icon,
                        iconLibrary: fallback.library
                    });
                });
            }
        }
    } else {
        console.log(`No existing ${type}s need enrichment (all have icons).`);
    }

    // 2. Generate NEW items
    if (countToGenerate > 0) {
        console.log(`Generating ${countToGenerate} new ${type}s...`);
        try {
            // Use a subset of known items for exclusions to avoid token limits
            const exclusionList = knownItemNames.slice(0, 100);

            const prompt = `
                Generate ${countToGenerate} NEW, distinct, and popular ${type}s that are meaningful and modern.
                Do NOT include these existing ones: ${JSON.stringify(exclusionList)}...
                For each new item, provide:
                - "name": The name of the ${type} (Capitalized).
                - "icon": A suitable icon name.
                - "iconLibrary": One of "MaterialCommunityIcons", "MaterialIcons", "FontAwesome", "Ionicons".
                
                Return a JSON object with a key "items" which is an array of these objects.
            `;

            const response = await getJsonCompletion<{ items: SeederItem[] }>(prompt);
            if (response && response.items) {
                // Validate icons before adding
                const validatedItems = validateSeederItems(response.items, type);
                results.push(...validatedItems);
            }
        } catch (e) {
            console.error(`Error generating new ${type}s:`, e);
        }
    }

    return results;
}

// ... existing code ...

export async function generateCoursesContextual(
    skills: string[],
    interests: string[],
    existingCourseNames: string[],
    countToGenerate: number = 20
): Promise<(SeederItem & { category: string })[]> {
    console.log(
        `Generating ${countToGenerate} courses based on ${skills.length} skills and ${interests.length} interests...`
    );

    // Limits inputs to avoid token overflow
    const skillContext = skills.slice(0, 50).join(", ");
    const interestContext = interests.slice(0, 30).join(", ");
    const exclusionList = existingCourseNames.slice(0, 100);

    try {
        const prompt = `
            I need to generate a list of relevant educational courses (degrees, diplomas, certifications) based on the following context:
            
            Top Skills: ${skillContext}...
            Top Interests: ${interestContext}...
            
            Generate ${countToGenerate} distinct, real-world course names that would help a user with these skills or interests.
            DO NOT include these existing courses: ${JSON.stringify(exclusionList)}...
            
            For each course, provide:
            - "name": The official name of the course (e.g., "B.Tech in Computer Science", "Certified Digital Marketer").
            - "category": A broad category for the course (e.g., "TECH", "COMMERCE", "ARTS", "MEDICAL", "DIPLOMA", "CERTIFICATION").
            - "icon": A suitable icon name from Expo Vector Icons.
            - "iconLibrary": One of "MaterialCommunityIcons", "MaterialIcons", "FontAwesome", "Ionicons".
            
            Output strictly in valid JSON format with structure:
            {
                "items": [
                    { "name": "Course Name", "category": "CATEGORY", "icon": "icon-name", "iconLibrary": "LibraryName" }
                ]
            }
        `;

        const response = await getJsonCompletion<{ items: (SeederItem & { category: string })[] }>(prompt);
        // Validate icons before returning
        const items = response?.items || [];
        return validateSeederItems(items, "course") as (SeederItem & { category: string })[];
    } catch (e) {
        console.error("Error generating contextual courses:", e);
        return [];
    }
}

export async function resolveCoursesAndGenerateNew(
    itemsToEnrich: { name: string; category: string }[],
    knownCourseNames: string[],
    skills: string[],
    interests: string[],
    countToGenerate: number = 20
): Promise<(SeederItem & { category: string })[]> {
    const results: (SeederItem & { category: string })[] = [];

    // 1. Enrich existing items
    if (itemsToEnrich.length > 0) {
        const chunkSize = 20;
        console.log(`Enriching ${itemsToEnrich.length} courses with icons...`);

        for (let i = 0; i < itemsToEnrich.length; i += chunkSize) {
            const chunk = itemsToEnrich.slice(i, i + chunkSize);
            try {
                const prompt = `
                    I have a list of courses: ${JSON.stringify(chunk)}.
                    For each course, provide:
                    - "name": The exact name from input.
                    - "category": The exact category from input.
                    - "icon": A suitable icon name from Expo Vector Icons.
                    - "iconLibrary": One of "MaterialCommunityIcons", "MaterialIcons", "FontAwesome", "Ionicons".
                    
                    Return JSON with key "items".
                `;
                const response = await getJsonCompletion<{ items: (SeederItem & { category: string })[] }>(prompt);
                if (response?.items) {
                    // Validate icons before adding
                    const validatedItems = validateSeederItems(response.items, "course") as (SeederItem & {
                        category: string;
                    })[];
                    results.push(...validatedItems);
                }
            } catch (e) {
                console.error(`Error enriching course chunk ${i}:`, e);
                // Fallback
                chunk.forEach((item) => results.push({ ...item, icon: "school", iconLibrary: "MaterialIcons" }));
            }
        }
    }

    // 2. Generate new
    if (countToGenerate > 0) {
        const newCourses = await generateCoursesContextual(skills, interests, knownCourseNames, countToGenerate);
        results.push(...newCourses);
    }

    return results;
}
